# Site settings
lang: en
styles: /assets/leetspeak.css
highlight: /assets/monokai.css
loading: /assets/loading.js

title: leetspeak
email: ping@leetspeak.tn
description: >-
  Open and collaborative content from TN hackers!
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
sass:
  style: compressed

highlighter: rouge
