# in the templates via {{ site.myvariable }}.
lang: en
styles: /assets/leetspeak.css
loading: /assets/loading.js

title: leetspeak
email: ping@leetspeak.tn
description: >- # this means to ignore newlines until "baseurl:"
  Open and collaborative content from TN hackers!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
