# Site settings
lang: en
title: leetspeek
email: ping@leetspeek.tn
description: >-
  Open and collaborative content from leet hackers!
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

sass:
  style: compressed

highlighter: rouge
